// IANA timezone → ISO 3166 region, for the regions CURRENCIES covers and no
// others. Feeds `currencyForTimeZone`, which turns it into a currency through
// the same region table `currencyForLocale` uses.
//
// Canonical zone names, plus the legacy aliases some browsers still report
// (Asia/Calcutta, America/Montreal, Europe/Nicosia). A zone missing
// from this table is a miss, which callers read as "fall through to the next
// signal", never as a guess.
//
// Deliberately absent: Europe/Busingen (Germany, but pays in CHF) and every
// zone shared by countries with different currencies.
export const TIME_ZONE_REGIONS: Record<string, string> = {
  // AED
  'Asia/Dubai': 'AE',
  // AUD
  'Australia/Sydney': 'AU',
  'Australia/Melbourne': 'AU',
  'Australia/Brisbane': 'AU',
  'Australia/Perth': 'AU',
  'Australia/Adelaide': 'AU',
  'Australia/Hobart': 'AU',
  'Australia/Darwin': 'AU',
  'Australia/Lindeman': 'AU',
  'Australia/Lord_Howe': 'AU',
  'Australia/Broken_Hill': 'AU',
  'Australia/Eucla': 'AU',
  // BRL
  'America/Sao_Paulo': 'BR',
  'America/Manaus': 'BR',
  'America/Fortaleza': 'BR',
  'America/Recife': 'BR',
  'America/Bahia': 'BR',
  'America/Belem': 'BR',
  'America/Maceio': 'BR',
  'America/Araguaina': 'BR',
  'America/Cuiaba': 'BR',
  'America/Campo_Grande': 'BR',
  'America/Porto_Velho': 'BR',
  'America/Boa_Vista': 'BR',
  'America/Rio_Branco': 'BR',
  'America/Eirunepe': 'BR',
  'America/Santarem': 'BR',
  'America/Noronha': 'BR',
  // CAD
  'America/Toronto': 'CA',
  'America/Vancouver': 'CA',
  'America/Edmonton': 'CA',
  'America/Winnipeg': 'CA',
  'America/Halifax': 'CA',
  'America/St_Johns': 'CA',
  'America/Regina': 'CA',
  'America/Moncton': 'CA',
  'America/Glace_Bay': 'CA',
  'America/Goose_Bay': 'CA',
  'America/Whitehorse': 'CA',
  'America/Dawson': 'CA',
  'America/Dawson_Creek': 'CA',
  'America/Fort_Nelson': 'CA',
  'America/Swift_Current': 'CA',
  'America/Cambridge_Bay': 'CA',
  'America/Inuvik': 'CA',
  'America/Iqaluit': 'CA',
  'America/Rankin_Inlet': 'CA',
  'America/Resolute': 'CA',
  'America/Montreal': 'CA',
  // CHF
  'Europe/Zurich': 'CH',
  'Europe/Vaduz': 'LI',
  // CZK
  'Europe/Prague': 'CZ',
  // DKK
  'Europe/Copenhagen': 'DK',
  // EUR
  'Europe/Vienna': 'AT',
  'Europe/Brussels': 'BE',
  'Europe/Zagreb': 'HR',
  'Asia/Nicosia': 'CY',
  'Asia/Famagusta': 'CY',
  'Europe/Nicosia': 'CY',
  'Europe/Tallinn': 'EE',
  'Europe/Helsinki': 'FI',
  'Europe/Paris': 'FR',
  'Europe/Berlin': 'DE',
  'Europe/Athens': 'GR',
  'Europe/Dublin': 'IE',
  'Europe/Rome': 'IT',
  'Europe/Riga': 'LV',
  'Europe/Vilnius': 'LT',
  'Europe/Luxembourg': 'LU',
  'Europe/Malta': 'MT',
  'Europe/Amsterdam': 'NL',
  'Europe/Lisbon': 'PT',
  'Atlantic/Madeira': 'PT',
  'Atlantic/Azores': 'PT',
  'Europe/Bratislava': 'SK',
  'Europe/Ljubljana': 'SI',
  'Europe/Madrid': 'ES',
  'Africa/Ceuta': 'ES',
  'Atlantic/Canary': 'ES',
  // GBP
  'Europe/London': 'GB',
  // HKD
  'Asia/Hong_Kong': 'HK',
  // HUF
  'Europe/Budapest': 'HU',
  // INR
  'Asia/Kolkata': 'IN',
  'Asia/Calcutta': 'IN',
  // JPY
  'Asia/Tokyo': 'JP',
  // MYR
  'Asia/Kuala_Lumpur': 'MY',
  'Asia/Kuching': 'MY',
  // NOK
  'Europe/Oslo': 'NO',
  // NZD
  'Pacific/Auckland': 'NZ',
  'Pacific/Chatham': 'NZ',
  // PLN
  'Europe/Warsaw': 'PL',
  // SEK
  'Europe/Stockholm': 'SE',
  // SGD
  'Asia/Singapore': 'SG',
  // USD
  'America/New_York': 'US',
  'America/Chicago': 'US',
  'America/Denver': 'US',
  'America/Los_Angeles': 'US',
  'America/Phoenix': 'US',
  'America/Anchorage': 'US',
  'America/Adak': 'US',
  'America/Boise': 'US',
  'America/Detroit': 'US',
  'America/Juneau': 'US',
  'America/Sitka': 'US',
  'America/Yakutat': 'US',
  'America/Nome': 'US',
  'America/Metlakatla': 'US',
  'America/Menominee': 'US',
  'America/Indiana/Indianapolis': 'US',
  'America/Indiana/Knox': 'US',
  'America/Indiana/Marengo': 'US',
  'America/Indiana/Petersburg': 'US',
  'America/Indiana/Tell_City': 'US',
  'America/Indiana/Vevay': 'US',
  'America/Indiana/Vincennes': 'US',
  'America/Indiana/Winamac': 'US',
  'America/Kentucky/Louisville': 'US',
  'America/Kentucky/Monticello': 'US',
  'America/North_Dakota/Beulah': 'US',
  'America/North_Dakota/Center': 'US',
  'America/North_Dakota/New_Salem': 'US',
  'Pacific/Honolulu': 'US',
};
