// Originally generated by Prisma; inert until the Prisma 6 upgrade, since
// config-file support only landed in 6.4. Two things follow from it now
// being read:
//
//  - Prisma no longer loads .env itself ("Prisma config detected, skipping
//    environment variable loading"), so the `dotenv/config` import below is
//    what supplies DATABASE_URL — and only from `.env` relative to cwd.
//    dotenv never overwrites an already-set var, so an explicit DATABASE_URL
//    (CI, Railway, the per-run test DB from src/__tests__/globalSetup.ts)
//    still wins.
//  - The paths below are relative to this file, but the file is only found
//    when the CLI runs with cwd = server/. The npm scripts do; an ad-hoc
//    `npx prisma …` from the repo root does not, and will behave differently.
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
